### PR TITLE
Split RDF-star and SPARQL-star manifests

### PR DESCRIPTION
**Pull request by afs**
Separate manifests for language and sparql tests (convenience for people who have different tools to run tests).

### CODE REVIEW

**Comment by afs** [comment]
I tried to provide manifest-X.jsonld files but the existing Turtle example "tests/turtle/manifest.jsonld" does not work for me. I guess because of relative URIs in the worker manifests. 

This PR include the trig in #147 which has other manifest changes. I'll come back to the JSONLD when that's in.

**Comment by gkellogg** [comment]
Note, we still have a single implementation report that reports on all tests, both SPARQL and concrete syntax. And the tests/index.html combines all the tests together.

Personally, I think this is appropriate, as the spec lists a single test suite and a single implementation report.

**Comment by gkellogg** [comment]
The logic for make-jsonld-manifests needs a slight tweak to generate the JSON-LD versions of these manifests, which I can do as a commit to this PR.

**Comment by gkellogg** [comment]
I rebased due to some conflicts.

**Comment by afs** [comment]
Now we have some experience of the implementation reports process, is this still work doing?

Maybe it's better to have just the per-directory manifests - less duplication, maintenance.

In practice, I have not been running from any of the top-level `manifest*` files.

**Comment by gkellogg** [comment]
We need the top-level HTML index, but that's built by hand. We could remove the manifest files in /tests, otherwise, but we should probably have them in sparql/, turtle/, and trig/ directories if we remove the top-level.

**Review by gkellogg — APPROVED** [review]

**Pull request merged**
