### PR TITLE
More syntax tests

### PR DESCRIPTION
**Pull request by afs**
Includes a bad syntax test for empty annotation.

### CODE REVIEW

**Comment by afs** [comment]
@gkellogg

**Comment by gkellogg** [comment]
@afs, only committers to the repo can be added as reviewers, which I apparently, am not. However, I can submit a review.

**Comment by afs** [comment]
Just to check the structure - the details of the tests are - obviously - for the whole community.

The interesting bit is the bad syntax test for empty annotation.

For a while, it thought "symmetry" (= tools generation) but realised that syntax that generated nothing was not useful.

**Review by gkellogg — APPROVED** [review]

**Comment by gkellogg** [comment]
It's consistent with `predicateObjectList` everyplace other than after a `blankNodePropertyList`, otherwise, we'd need `"{|" predicateObjectList? "|}"` which does, indeed, seem pointless.

**Comment by josd** [comment]
+1 and EYE is currently throwing an empty_triple_annotation exception
The other test results are at https://github.com/josd/eye/blob/master/reasoning/rdf-star/run-outcome.n3

BTW @afs thanks for riot without which we would not be able to run https://github.com/josd/eye/blob/master/reasoning/rdf-star/run-test

**Pull request merged**
