### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by afs**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/pull/190.html" title="Last updated on Jun 14, 2021, 9:36 AM UTC (403eafb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-star/190/561ce51...403eafb.html" title="Last updated on Jun 14, 2021, 9:36 AM UTC (403eafb)">Diff</a>

### CODE REVIEW

**Comment by afs** [comment]
Fixing reSpec workflow links. 

There may be some noise on this PR - it's the only way I have to test the changes.

**Comment by afs** [comment]
Fixed some links but not all

Fixed:
```
    page not found from editors_draft.html to combining-rdf-star-graphs
    anchor not found from editors_draft.html to N-TRIPLES#grammar-production-triple
    anchor not found from editors_draft.html to rdf-sparql-XMLres#results
```

but not the errors:

```
    page not found from editors_draft.html to ../tests/index.html
    page not found from editors_draft.html to ../UCR/rdf-star-ucr.html#annotate-statements-from-other-named-graphs-and-datasets
    page not found from editors_draft.html to ../UCR/rdf-star-ucr.html#annotate-commit-deltas
    page not found from editors_draft.html to ../UCR/rdf-star-ucr.html#meta-properties-over-properties
```
Using  `/UCR/...` etc changes the errors to 
```
    page not found from editors_draft.html to UCR/rdf-star-ucr.html#
```
note - no "/".

**Comment by gkellogg** [comment]
I reported a bug against w3c/spec-prod action. This seems to be a problem, with link-checker, probably because it doesn’t use a local,server, and can’t load local references.

https://github.com/w3c/spec-prod/issues/86

**Comment by afs** [comment]
After the mention on Friday, I didn't try much out on the "../" - good to know it has reported.

The fixed ones are actual errors - I just don't understand why they have appeared now when as far as I can see they aren't new. The fixes do work for them at least.

**Review by pchampin — APPROVED** [review]

**Comment by gkellogg** [comment]
> After the mention on Friday, I didn't try much out on the "../" - good to know it has reported.
> 
> The fixed ones are actual errors - I just don't understand why they have appeared now when as far as I can see they aren't new. The fixes do work for them at least.

This probably duplicates some fixes I made in #188. The link checker does, indeed, find real problems, which is good; it just doesn't handle relative links properly, which also affects the N3 spec, as well as many others.

**Review by gkellogg — APPROVED** [review]

**Pull request closed without merging**
