### PR TITLE
More combinations on embedded syntax

### PR DESCRIPTION
**Pull request by gkellogg**
@afs I didn't see a script for generating manifest.jsonld from manifest.ttl; I updated sparql/syntax/manifest.jsonld by hand, but didn't update turtle/eval/manifest.jsonld. I did build the HTML versions, however.

### CODE REVIEW

**Review by afs — APPROVED** [review]

**Comment by afs** [comment]
I don't have a script - the "semi-mechanical" process I used was to convert manifest.ttl to JSON-LD using jsonld-java (via Jena `riot --pretty jsonld`) then manually edit to make it nicer as JSON - inlining the tests into the entries array (separate objects otherwise) and making URIs relative.

From then on, it a matter of copying and new tests into manifest.json, with the fragment taken from a new run of `riot --pretty jsonld` - they does produce the right fragment apart from the absolute `@id`.

Then check they produce the same RDF and also run the same tests.

**Comment by gkellogg** [comment]
Okay, I have a script that does that too. I’ll regenerate and push up.

**Review by pchampin — APPROVED** [review]
Looking good to me. Do you (@afs @gkellogg @hartig) think that we should discuss this PR on call time?

**Comment by gkellogg** [comment]
I don’t think it warrants call time, it’s just adding coverage. The details for how the manifests are managed shouldn’t affect anyone.

**Pull request merged**
