### PR TITLE
Add telecon time to home page.

### PR DESCRIPTION
**Pull request by afs**

### CODE REVIEW

**Comment by TallTed** [comment]
Seems to partially duplicate #61

**Comment by afs** [comment]
Yes - this is just about the telecons and about not rewriting other text.

**Comment by TallTed** [comment]
I don't understand why you would create a new PR for that, instead of suggesting changes to the existing PR which changes the same snippet.

**Comment by afs** [comment]
Because #61 is trying to change the name of the entire endeavour and that is obstructing making this small, unrelated change.

**Comment by TallTed** [comment]
#61 is gone, due to an accidental fork deletion.

#74 revises the text, to not rename but still incorporate the "rdf star" lexical, so that clever web searchers who figure out that they should replace `*` with `star` have a chance of finding it.

#74 also includes the meeting details that were ignored in #61 because the naming issue was so blinding.

**Comment by pchampin** [comment]
superceded by #74

**Pull request closed without merging**
