### PR TITLE
Update generated implementation report, and improve build process

### LINKED ISSUE #233: Test report generator failure
In an up-to-date repo, `bundle install` and `bundle exec rake` run fine.

But I tried to add a new EARL report `apache-jena.ttl` I get errors relating to `"http://champin.net/#pa"` which isn't in the file.
(draft [apache-jena.ttl.txt](https://github.com/w3c/rdf-star/files/7739236/apache-jena.ttl.txt) attached - with `.txt` added for GH).

How can I debug this?

_Update_: PR #235 works - the difference is "homepage" URIs changed from "http:" to "https:" and if the timestamp of the file is later than all files in the directory. Restoring earl.* from git does not leave timestamps in the right state.

```
Traceback (most recent call last):
	9: from /home/afs/gems/bin/earl-report:23:in `<main>'
	8: from /home/afs/gems/bin/earl-report:23:in `load'
	7: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/bin/earl-report:100:in `<top (required)>'
	6: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:479:in `generate'
	5: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:559:in `earl_turtle'
	4: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:559:in `each'
	3: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:565:in `block in earl_turtle'
	2: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:565:in `each'
	1: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:566:in `block (2 levels) in earl_turtle'
/var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:574:in `ttl_entity': undefined method `map' for "http://champin.net/#pa":String (NoMethodError)
```

If I rename the file to `jena.ttl, I get 
```
Traceback (most recent call last):
	11: from /home/afs/gems/bin/earl-report:23:in `<main>'
	10: from /home/afs/gems/bin/earl-report:23:in `load'
	 9: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/bin/earl-report:100:in `<top (required)>'
	 8: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:495:in `generate'
	 7: from /var/lib/gems/2.7.0/gems/haml-5.2.1/lib/haml/engine.rb:130:in `render'
	 6: from /var/lib/gems/2.7.0/gems/haml-5.2.1/lib/haml/engine.rb:130:in `eval'
	 5: from (haml):343:in `block in render'
	 4: from (haml):343:in `each_with_index'
	 3: from (haml):343:in `each'
	 2: from (haml):374:in `block (2 levels) in render'
	 1: from (haml):374:in `each'
(haml):377:in `block (3 levels) in render': undefined method `has_key?' for "http://champin.net/#pa":String (NoMethodError)
```

### PR DESCRIPTION
**Pull request by gkellogg**
Updates version of earl-report to 0.7.1, which fixes a problem in loading the FOAF profile when there are multiple developers.

In CI, do a clean build of the reports.

Regenerate the published report.

Fixes #233.

### CODE REVIEW

**Comment by afs** [comment]
Does the README need changing to be:

```sh
$ bundle install
$ bundle exec rake clean default
```

**Comment by gkellogg** [comment]
The `rake clean` isn't really necessary for a normal build, and the updated dependency for the earl-report gem cleans up any inconsistency. The use of the `rake clean` in CI just makes sure that everything is built, and not just the dependencies based on file date.

**Review by pchampin — APPROVED** [review]
The generation of the report works on my machine with this PR applied.

That being said, it also works without this PR, while the CI chokes on it. So maybe that proves nothing...

**Comment by gkellogg** [comment]
Actually, there was a problem where the FOAF information was not gathered consistently when there is more than one developer for a project due to inherent randomness of triple ordering. The bug fix in the earl-report software was to use an ordered RDF repository, and to ensure that any FOAF information is gathered for all entries, not just the first.

**Pull request merged**
