### PR TITLE
 feat: add negative tests for annotation syntax in nt

### PR DESCRIPTION
**Pull request by jeswr**
@afs Do the manifest.ttl and manifest.jsonld both need to be manually updated in this repo - or is there some kind of automation I should be running to update them?

### CODE REVIEW

**Comment by afs** [comment]
manifest.ttl needs to be updated.

A conversion to json-ld would be nice (Turtle can have `#` comments).

**Comment by gkellogg** [comment]
Note that w3c/rdf-tests#95 is intended to automatically update manifest.jsonld and the associated HTML version in each PR from manifest.ttl. This is similar to how it's done in https://github.com/w3c/rdf-canon/blob/main/.github/workflows/generate.yml. In RCH, any time something is touched in the tests or reports directory, it re-builds the dependent files and pushes up a new commit to the PR.

**Comment by afs** [comment]
I've checked the tests and executed manifest.ttl - all OK. So this PR is ready. Thanks!

This is the rdf-star (CG) repo. 

The tests will eventually end up in [rdf-tests](https://github.com/w3c/rdf-tests) but maybe not directly. The RDF -star WG may wish (or even need) to have it's own test area so that it can mark them as the test suite at the end of the working group.

I've emailed the WG to get the process details agreed upon.

https://lists.w3.org/Archives/Public/public-rdf-star-wg/2023Jun/0034.html

**Review by gkellogg — APPROVED** [review]

**Comment by jeswr** [comment]
Awesome - I don't have permissions to merge on this repo so @gkellogg @afs you can go ahead and do this yourselves when you're ready.

**Comment by afs** [comment]
The WG still has to work out the over details but for now, merging to the CG repo is OK.

Thanks!

**Pull request merged**
